version: '3.3'

services:

  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  test:
    container_name: test
    build:
      context: ./backend/.
      dockerfile: ./Dockerfile-test
    image: test:latest
    ports:
      - '6201:6201'
    environment:
      - NODE_ENV=test
    volumes:
      - ./backend/__tests__:/app/__tests__
      - ./backend/src:/app/src
      - ./backend/setupTests.js:/app/setupTests.js
    depends_on:
      - mongodb
